version: "3.9"

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: llvm-obfuscator-backend
    environment:
      - OBFUSCATOR_DISABLE_AUTH=false
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    expose:
      - "8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - obfuscator-network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    container_name: llvm-obfuscator-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - obfuscator-network

  # Optional: Add nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: llvm-obfuscator-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - obfuscator-network

networks:
  obfuscator-network:
    driver: bridge

volumes:
  reports:
    driver: local
  logs:
    driver: local

